# Generated by Django 5.1 on 2024-08-29 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="location"),
                ),
                ("time", models.TimeField(verbose_name="time")),
                (
                    "action",
                    models.CharField(max_length=100, verbose_name="action"),
                ),
                ("is_pleasant", models.BooleanField(verbose_name="pleasant")),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="periodicity"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reward"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(verbose_name="duration"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="public"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="related habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "habit",
                "verbose_name_plural": "habits",
            },
        ),
    ]
